### ISSUE TITLE
Slider still jumping all over the place when sliding back and forth using step={1}

### ISSUE THREAD

**Issue by schumannd** [react-native-community/react-native-slider#131] opened 2019-11-19 12:57 UTC
This used to be an issue #109 for users using old react native versions. Now that we updated, the issue still seems to persist.

Using the latest version:

    "@react-native-community/slider": "2.0.3",
    "react-native": "0.61.4",

**Comment by Krizzu** [comment] 2019-11-25 10:13
@schumannd What iOS version have you tested?

**Comment by schumannd** [comment] 2019-11-25 12:21
iOS 13.1.2

**Comment by michalchudziak** [comment] 2019-11-26 11:04
This issue should be fixed in version `2.0.6`. Please check it out and re-open this if it still occurs :)

**Closed by michalchudziak** 2019-11-26 11:04 UTC
Labels: bug report

**Comment by schumannd** [comment] 2019-11-26 12:54
It was an issue caused by my handling of onValueChange to begin with. Thanks for your help!

**Comment by joshbg2k** [comment] 2019-12-04 23:52
> It was an issue caused by my handling of onValueChange to begin with. So it probably wasn't broken in the end. Thanks for your help!

@schumannd How did you handle it? I have the same issue but with RN 0.55.4.

**Comment by schumannd** [comment] 2019-12-05 07:33
@joshbg2k actually we didn't.

The issue arises for us, if we add any state update to the `onValueChange` vs. `currentValue` loop. Removing this, or only using `onSlidingComplete` avoids the problem. For us this was not an option though, as we want a "speech bubble" to always stay with the sliding head. Is this situation similar to yours?

**Comment by joshbg2k** [comment] 2019-12-05 19:16
@schumannd Yeah it's really similar. My slider enables a range of values in steps, so when the user slides in either direction, the label for each step changes based on it being enabled or disabled, so I use `onValueChange` to update the state and manage that. So I think we're both in the same boat - we want richer user feedback _while_ the user is using the slider. Looks like I'll have to use `onSlidingComplete` and update multiple labels at once at the end of the interaction. Not ideal but at least the feature will be usable until a fix or alternative is available.

**Comment by schumannd** [comment] 2019-12-05 19:52
@joshbg2k, @michalchudziak I would say it is not fixed then. It used to work before we updated to RN 61.4. So it might be related to a change in how RN updates state. I also couldn't find any reference to `currentValue` in the README. Is that not supported anymore? Maybe that's where the issue lies.

**Comment by lkoehl** [comment] 2019-12-16 20:03
For me the slider also jumps around, but also when step > 1. It doesn't change if I don't set the state in ```onValueChange```. For right now I needed to switch to another slider library. 
Also I am using the latest version ```2.0.8```.

**Comment by Jason-Cooke** [comment] 2020-05-14 21:21
@michalchudziak Could we reopen this please?

**Comment by mikehardy** [comment] 2020-07-04 18:31
I was unable to reproduce any jumping around with the current example, if anyone is still experiencing this perhaps they could extend the example to demonstrate it? Without a demo it's hard to reproduce.
Separately if people want the tap-to-click feature that caused the jumping around I think I have the implemented correctly in pending PR #201  with a patch attached to it so you may try it out
